[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
# console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.80"
yew = { version="0.19.3"}
yew-router = { version = "0.16.0"}
# web-sys = "0.3"
# yew_styles = { version="0.11", features = ["navbar"]}
# stylist = "0.10.0"