apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: kainotomia
build:
  local:
    concurrency: 0
  artifacts:
  - image: ghcr.io/hown3d/kainotomia/job
    ko:
      main: "./cmd/job"
      ldflags: 
        - -s -w
      dependencies:
        paths: ["**/*.go"]
        ignore: ["./cmd/server/**/*"]
  - image: ghcr.io/hown3d/kainotomia/server
    ko:
      main: "./cmd/server"
      ldflags: 
        - -s -w
      dependencies:
        paths: ["**/*.go"]
        ignore: ["./cmd/job/**/*"]
deploy:
  helm:
    releases:
      - name: test
        artifactOverrides:
          jobImage: ghcr.io/hown3d/kainotomia/job
          image: ghcr.io/hown3d/kainotomia/server
        chartPath: helm-chart/kainotomia
        imageStrategy:
          helm: {}

profiles:
  - name: debug
    patches:
      - op: replace
        path: /build/artifacts/0/ko/fromImage
        value: gcr.io/distroless/static:debug-nonroot

